version: "3"
services:
  app:
    build: ./
    restart: always
    container_name: camp
    ports:
      - ${APP_PORT}:3000
    networks:
      - camp-network
networks:
  camp-network:
    external:
      name: camp
